### ISSUE TITLE
SPI case names with embedded &'s are not handled properly

### ISSUE THREAD

**Issue by roysmith** [roysmith/spi-tools#205]
See https://en.wikipedia.org/wiki/Wikipedia:Sockpuppet_investigations/Jiboner%26to.  Selecting SPI Tools from the More menu gets you to https://spi-tools.toolforge.org/spi/?caseName=Jiboner&to

**Comment by Dreamy-Jazz** [comment]
The fix for this is to use encodeURIComponent() on the caseName so that & et. al. that make up a URL are escaped. Using just encodeURI does not escape the & character amongst others that should be escaped if this is a component in a URL.
