### ISSUE TITLE
Non-admins can't view any contributions

### ISSUE THREAD

**Issue by mdaniels5757** [roysmith/spi-tools#79]
Steps to reproduce:
* As a non-admin, visit any user's user-info page (e.g. <https://spi-tools.toolforge.org/spi/spi-user-info/UltraUsurper/>)
* Click go

Expected results:
* Non-deleted contributions show up
* Deleted contributions do not (although it'd be nice if we could show whether there are any a la xtools)

Actual results:
`Something went wrong when fetching user contributions (and deleted contributions). The error was "permissiondenied" (You don't have permission to view deleted comments.).`

**Comment by roysmith** [comment]
Thanks for the report.

Yeah, I see what's happening there.  I'll probably get that resolved in the next couple of days.

**Comment by roysmith** [comment]
This is now deployed to https://spi-tools.toolforge.org.  Thank you again for reporting the problem.
